services:
  chainlit:
    platform: "linux/amd64"
    build:
      dockerfile: ".chainlit/Dockerfile"
    environment:
      # - OLLAMA_URL=http://ollama:11434
      # - QDRANT_DATABASE_URL=http://qdrantdb:6333
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_DATABASE_URL=http://qdrantdb:6333
      - DATA_INGESTION_LOCATION=/data
    volumes:
      - chainlit:/code/.files
      - ./utils:/code/app/utils
      - ./data:/data
      - ./main.py:/code/app/main.py
      - ./config.py:/code/app/config.py


    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - ollama
      - qdrantdb
      - n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.45.1
    environment:
      - N8N_LOG_LEVEL=info
      - N8N_PORT=5678
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data_n8n:/data
    restart: always
 
  qdrantdb:
    image: qdrant/qdrant:${QDRANT_TAG:-latest}
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage:z
    restart: always

  ollama:
    image: ollama/ollama:${OLLAMA_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    # Enable GPU support using host machine
    # https://docs.docker.com/compose/how-tos/gpu-support/
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [ gpu ]


volumes:
  chainlit:
  ollama:
  qdrant_storage:
  n8n_data:
